### ISSUE TITLE
Two date picker when datepicker opens

### ISSUE THREAD

**Issue by PouyaKrm** [rzkhosroshahi/zaman#73] opened 2022-10-19 15:44 UTC
Hi.
When I click on the date picker, it contains two date pickers that are under each other

**Comment by Ehsan-heydari** [comment] 2022-11-28 05:39
Hi ,Me too 
Did you find a way?

**Comment by ahmad-shoja** [comment] 2022-12-20 17:33
> Hi. When I click on the date picker, it contains two date pickers that are under each other

Hi, can you explain how its happening? how can I to reproduce the bug?

**Comment by PouyaKrm** [comment] 2022-12-20 18:33
The first time I open the date picker, It produces this bug. 
After it gets closed and reopened again, it appears normal.

**Comment by rzkhosroshahi** [comment] 2023-03-29 08:13
Hey 👋🏻
Here's an announcement that a new version of the module has just been released. Since this issue is related to the older version, I have closed it. I would appreciate your feedback on the new version.

**Closed by rzkhosroshahi** 2023-03-29 08:13 UTC
